name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"   # Runs daily at midnight
  workflow_dispatch:      # Allows manual run

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Pac-Man Graph
        uses: Platane/snk@v3
        with:
          github_user_name: hawisamuel
          outputs: |
            pacman-contribution-graph.svg?palette=github-dark

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: output
          keep_files: false
